services:
  - type: web
    name: nbp-gus-qa
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: JINA_API_KEY
        sync: false
